### PR TITLE
Add informations indicating to not translate icon file name

### PR DESCRIPTION
**Pull request by tamplan**
Indicates to people to not translate icon file name in directory file.

### CODE REVIEW

**Comment by tamplan** [comment]
I think i miss to change the "mate-menus.pot".

Did someone can help me about this (explain me how to do)?

Thanks by advance.

Regards.

**Comment by raveit65** [comment]
> I think i miss to change the "mate-menus.pot".
> 
> Did someone can help me about this (explain me how to do)?
> 
> Thanks by advance.
> 
> Regards.

No, not needed to edit this file. From time to time we do that for ourself, mostly before a release.
Keep in mind that every small update of this file trigger a notification for translator when commited.
The file will be updated with `./autogen.sh && ./makepot`

**Comment by tamplan** [comment]
Ok, thanks for the tips.

Perhaps, the PR can be closed.

**Comment by raveit65** [comment]
Why closing?
I talked about mate-menus.pot
In general we fixed the problem of translated icon-names with this commit https://github.com/mate-desktop/mate-menus/commit/39c11887c2fc8098eff2fa77163f85b90df6212a
But adding translator hints might be a good idea.

**Comment by tamplan** [comment]
Ok, so, let's it open.

I understand i don't need to provide more change on files.

Thanks.

**Comment by raveit65** [comment]
No idea why but translator hints won't be added to mate-menus.pot.
Try for yourself with
`./autogen.sh && ./makepot && grep -nr transliterate mate-menus.pot`

PS: i am getting more and more tired to spend my spare time to review things which aren't really needed.

**Comment by tamplan** [comment]
> ./autogen.sh && ./makepot && grep -nr transliterate mate-menus.pot

This does nothing, transliterate is not in mate-menus.pot.

> PS: i am getting more and more tired to spend my spare time to review things which aren't really needed.
Sorry if you think this bug is not critical unless you consider that it lacks a help message for the translation of .po files, avoiding thereafter the opening of future issues here relating to the translation whatever the tool used (transifex site or software)

You can leave this PR open, i can invintigate more comparing with others repositories here.

**Comment by raveit65** [comment]
> Sorry if you think this bug is not critical unless you consider that it lacks a help message for the translation of .po files, avoiding thereafter the opening of future issues here relating to the translation whatever the tool used (transifex site or software)

Again, Issue was fixed by https://github.com/mate-desktop/mate-menus/commit/39c11887c2fc8098eff2fa77163f85b90df6212a
So, what issue you want to fix?

**Comment by tamplan** [comment]
I just answer to your message after launching the command you give me, i will try again later after controlling my local repository is update but for me, transliterate is not in mate-menus.pot.

As purpose, please, let's this PR open, i'll give you feedback soon, i think you and me have, perhaps, some else to do for the moment...

**Pull request closed without merging**
