### PR TITLE
meson build system

### PR DESCRIPTION
**Pull request by yetist**
This PR depends on #115

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
On configuration I got these warnings:
```
WARNING: Project specifies a minimum meson_version '>=0.47.0' but uses features which were added in newer versions:
 * 0.49.0: {'/ with string arguments'}
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.build_root'}

```
other than that, this builds, installs, and ininstall fine. I don't know anything about the tests referenced so no opinion there

**Comment by lukefromdc** [comment]
On running 
meson build --prefix=/usr (old syntax and what I know how to use)

I got this error:
`meson.build:47:3: ERROR: Tried to access unknown option 'collection'.`

**Comment by yetist** [comment]
> On running meson build --prefix=/usr (old syntax and what I know how to use)
> 
> I got this error: `meson.build:47:3: ERROR: Tried to access unknown option 'collection'.`

Please check `meson_options.txt` file, I add the `collection` option in it.
```
$ grep collection meson_options.txt
```

**Comment by lukefromdc** [comment]
This has now gotten more complex, this is a retest from scratch w the previous PR dependency etc

**Comment by lukefromdc** [comment]
I will have to make a local "dev-test" branch for this it seems

**Comment by lukefromdc** [comment]
The combined test branch (this applied on top of #115) builds with a bucket of "unknown namespace" warnings but does install and run (menu works normally on the mate-panel button menu). 
Used this configuration command:
`meson setup build --prefix=/usr`

Here are the warnings I got:
```

[160/161] Generating libmenu/MateMenu-2.0....stom command (wrapped by meson to set env)
../libmenu/desktop-entries.h:32: Warning: MateMenu: symbol='DesktopEntryType': Unknown namespace for identifier 'DesktopEntryType'
../libmenu/desktop-entries.h:34: Warning: MateMenu: symbol='DesktopEntry': Unknown namespace for identifier 'DesktopEntry'
../libmenu/desktop-entries.h:36: Warning: MateMenu: symbol='desktop_entry_new': Unknown namespace for symbol 'desktop_entry_new'
../libmenu/desktop-entries.h:38: Warning: MateMenu: symbol='desktop_entry_ref': Unknown namespace for symbol 'desktop_entry_ref'
../libmenu/desktop-entries.h:39: Warning: MateMenu: symbol='desktop_entry_copy': Unknown namespace for symbol 'desktop_entry_copy'
../libmenu/desktop-entries.h:40: Warning: MateMenu: symbol='desktop_entry_reload': Unknown namespace for symbol 'desktop_entry_reload'
../libmenu/desktop-entries.h:41: Warning: MateMenu: symbol='desktop_entry_unref': Unknown namespace for symbol 'desktop_entry_unref'
../libmenu/desktop-entries.h:43: Warning: MateMenu: symbol='desktop_entry_get_type': Unknown namespace for symbol 'desktop_entry_get_type'
../libmenu/desktop-entries.h:44: Warning: MateMenu: symbol='desktop_entry_get_path': Unknown namespace for symbol 'desktop_entry_get_path'
../libmenu/desktop-entries.h:45: Warning: MateMenu: symbol='desktop_entry_get_basename': Unknown namespace for symbol 'desktop_entry_get_basename'
../libmenu/desktop-entries.h:46: Warning: MateMenu: symbol='desktop_entry_get_name': Unknown namespace for symbol 'desktop_entry_get_name'
../libmenu/desktop-entries.h:47: Warning: MateMenu: symbol='desktop_entry_get_generic_name': Unknown namespace for symbol 'desktop_entry_get_generic_name'
../libmenu/desktop-entries.h:48: Warning: MateMenu: symbol='desktop_entry_get_comment': Unknown namespace for symbol 'desktop_entry_get_comment'
../libmenu/desktop-entries.h:49: Warning: MateMenu: symbol='desktop_entry_get_icon': Unknown namespace for symbol 'desktop_entry_get_icon'
../libmenu/desktop-entries.h:50: Warning: MateMenu: symbol='desktop_entry_get_hidden': Unknown namespace for symbol 'desktop_entry_get_hidden'
../libmenu/desktop-entries.h:51: Warning: MateMenu: symbol='desktop_entry_get_no_display': Unknown namespace for symbol 'desktop_entry_get_no_display'
../libmenu/desktop-entries.h:52: Warning: MateMenu: symbol='desktop_entry_get_show_in': Unknown namespace for symbol 'desktop_entry_get_show_in'
../libmenu/desktop-entries.h:55: Warning: MateMenu: symbol='desktop_entry_get_app_info': Unknown namespace for symbol 'desktop_entry_get_app_info'
../libmenu/desktop-entries.h:56: Warning: MateMenu: symbol='desktop_entry_has_categories': Unknown namespace for symbol 'desktop_entry_has_categories'
../libmenu/desktop-entries.h:57: Warning: MateMenu: symbol='desktop_entry_has_category': Unknown namespace for symbol 'desktop_entry_has_category'
../libmenu/desktop-entries.h:60: Warning: MateMenu: symbol='desktop_entry_add_legacy_category': Unknown namespace for symbol 'desktop_entry_add_legacy_category'
../libmenu/desktop-entries.h:62: Warning: MateMenu: symbol='DesktopEntrySet': Unknown namespace for identifier 'DesktopEntrySet'
../libmenu/desktop-entries.h:64: Warning: MateMenu: symbol='desktop_entry_set_new': Unknown namespace for symbol 'desktop_entry_set_new'
../libmenu/desktop-entries.h:65: Warning: MateMenu: symbol='desktop_entry_set_ref': Unknown namespace for symbol 'desktop_entry_set_ref'
../libmenu/desktop-entries.h:66: Warning: MateMenu: symbol='desktop_entry_set_unref': Unknown namespace for symbol 'desktop_entry_set_unref'
../libmenu/desktop-entries.h:68: Warning: MateMenu: symbol='desktop_entry_set_add_entry': Unknown namespace for symbol 'desktop_entry_set_add_entry'
../libmenu/desktop-entries.h:69: Warning: MateMenu: symbol='desktop_entry_set_lookup': Unknown namespace for symbol 'desktop_entry_set_lookup'
../libmenu/desktop-entries.h:70: Warning: MateMenu: symbol='desktop_entry_set_get_count': Unknown namespace for symbol 'desktop_entry_set_get_count'
../libmenu/desktop-entries.h:72: Warning: MateMenu: symbol='desktop_entry_set_union': Unknown namespace for symbol 'desktop_entry_set_union'
../libmenu/desktop-entries.h:73: Warning: MateMenu: symbol='desktop_entry_set_intersection': Unknown namespace for symbol 'desktop_entry_set_intersection'
../libmenu/desktop-entries.h:74: Warning: MateMenu: symbol='desktop_entry_set_subtract': Unknown namespace for symbol 'desktop_entry_set_subtract'
../libmenu/desktop-entries.h:75: Warning: MateMenu: symbol='desktop_entry_set_swap_contents': Unknown namespace for symbol 'desktop_entry_set_swap_contents'
../libmenu/desktop-entries.h:77: Warning: MateMenu: symbol='DesktopEntrySetForeachFunc': Unknown namespace for identifier 'DesktopEntrySetForeachFunc'
../libmenu/desktop-entries.h:79: Warning: MateMenu: symbol='desktop_entry_set_foreach': Unknown namespace for symbol 'desktop_entry_set_foreach'
../libmenu/entry-directories.h:29: Warning: MateMenu: symbol='EntryDirectory': Unknown namespace for identifier 'EntryDirectory'
../libmenu/entry-directories.h:31: Warning: MateMenu: symbol='EntryDirectoryChangedFunc': Unknown namespace for identifier 'EntryDirectoryChangedFunc'
../libmenu/entry-directories.h:33: Warning: MateMenu: symbol='entry_directory_new': Unknown namespace for symbol 'entry_directory_new'
../libmenu/entry-directories.h:34: Warning: MateMenu: symbol='entry_directory_new_legacy': Unknown namespace for symbol 'entry_directory_new_legacy'
../libmenu/entry-directories.h:36: Warning: MateMenu: symbol='entry_directory_ref': Unknown namespace for symbol 'entry_directory_ref'
../libmenu/entry-directories.h:37: Warning: MateMenu: symbol='entry_directory_unref': Unknown namespace for symbol 'entry_directory_unref'
../libmenu/entry-directories.h:39: Warning: MateMenu: symbol='entry_directory_get_flat_contents': Unknown namespace for symbol 'entry_directory_get_flat_contents'
../libmenu/entry-directories.h:42: Warning: MateMenu: symbol='EntryDirectoryList': Unknown namespace for identifier 'EntryDirectoryList'
../libmenu/entry-directories.h:44: Warning: MateMenu: symbol='entry_directory_list_new': Unknown namespace for symbol 'entry_directory_list_new'
../libmenu/entry-directories.h:45: Warning: MateMenu: symbol='entry_directory_list_ref': Unknown namespace for symbol 'entry_directory_list_ref'
../libmenu/entry-directories.h:46: Warning: MateMenu: symbol='entry_directory_list_unref': Unknown namespace for symbol 'entry_directory_list_unref'
../libmenu/entry-directories.h:48: Warning: MateMenu: symbol='entry_directory_list_get_length': Unknown namespace for symbol 'entry_directory_list_get_length'
../libmenu/entry-directories.h:51: Warning: MateMenu: symbol='entry_directory_list_prepend': Unknown namespace for symbol 'entry_directory_list_prepend'
../libmenu/entry-directories.h:52: Warning: MateMenu: symbol='entry_directory_list_append_list': Unknown namespace for symbol 'entry_directory_list_append_list'
../libmenu/entry-directories.h:54: Warning: MateMenu: symbol='entry_directory_list_add_monitors': Unknown namespace for symbol 'entry_directory_list_add_monitors'
../libmenu/entry-directories.h:55: Warning: MateMenu: symbol='entry_directory_list_remove_monitors': Unknown namespace for symbol 'entry_directory_list_remove_monitors'
../libmenu/entry-directories.h:57: Warning: MateMenu: symbol='entry_directory_list_get_directory': Unknown namespace for symbol 'entry_directory_list_get_directory'
../libmenu/menu-layout.h:32: Warning: MateMenu: symbol='MenuLayoutNode': Unknown namespace for identifier 'MenuLayoutNode'
../libmenu/menu-layout.h:69: Warning: MateMenu: symbol='MenuLayoutNodeType': Unknown namespace for identifier 'MenuLayoutNodeType'
../libmenu/menu-layout.h:74: Warning: MateMenu: symbol='MenuMergeFileType': Unknown namespace for identifier 'MenuMergeFileType'
../libmenu/menu-layout.h:81: Warning: MateMenu: symbol='MenuLayoutMergeType': Unknown namespace for identifier 'MenuLayoutMergeType'
../libmenu/menu-layout.h:90: Warning: MateMenu: symbol='MenuLayoutValuesMask': Unknown namespace for identifier 'MenuLayoutValuesMask'
../libmenu/menu-layout.h:101: Warning: MateMenu: symbol='MenuLayoutValues': Unknown namespace for identifier 'MenuLayoutValues'
../libmenu/menu-layout.h:104: Warning: MateMenu: symbol='menu_layout_load': Unknown namespace for symbol 'menu_layout_load'
../libmenu/menu-layout.h:106: Warning: MateMenu: symbol='menu_layout_node_new': Unknown namespace for symbol 'menu_layout_node_new'
../libmenu/menu-layout.h:107: Warning: MateMenu: symbol='menu_layout_node_ref': Unknown namespace for symbol 'menu_layout_node_ref'
../libmenu/menu-layout.h:108: Warning: MateMenu: symbol='menu_layout_node_unref': Unknown namespace for symbol 'menu_layout_node_unref'
../libmenu/menu-layout.h:110: Warning: MateMenu: symbol='menu_layout_node_get_type': Unknown namespace for symbol 'menu_layout_node_get_type'
../libmenu/menu-layout.h:112: Warning: MateMenu: symbol='menu_layout_node_get_root': Unknown namespace for symbol 'menu_layout_node_get_root'
../libmenu/menu-layout.h:113: Warning: MateMenu: symbol='menu_layout_node_get_parent': Unknown namespace for symbol 'menu_layout_node_get_parent'
../libmenu/menu-layout.h:114: Warning: MateMenu: symbol='menu_layout_node_get_children': Unknown namespace for symbol 'menu_layout_node_get_children'
../libmenu/menu-layout.h:115: Warning: MateMenu: symbol='menu_layout_node_get_next': Unknown namespace for symbol 'menu_layout_node_get_next'
../libmenu/menu-layout.h:117: Warning: MateMenu: symbol='menu_layout_node_insert_before': Unknown namespace for symbol 'menu_layout_node_insert_before'
../libmenu/menu-layout.h:118: Warning: MateMenu: symbol='menu_layout_node_insert_after': Unknown namespace for symbol 'menu_layout_node_insert_after'
../libmenu/menu-layout.h:119: Warning: MateMenu: symbol='menu_layout_node_prepend_child': Unknown namespace for symbol 'menu_layout_node_prepend_child'
../libmenu/menu-layout.h:120: Warning: MateMenu: symbol='menu_layout_node_append_child': Unknown namespace for symbol 'menu_layout_node_append_child'
../libmenu/menu-layout.h:122: Warning: MateMenu: symbol='menu_layout_node_unlink': Unknown namespace for symbol 'menu_layout_node_unlink'
../libmenu/menu-layout.h:123: Warning: MateMenu: symbol='menu_layout_node_steal': Unknown namespace for symbol 'menu_layout_node_steal'
../libmenu/menu-layout.h:125: Warning: MateMenu: symbol='menu_layout_node_get_content': Unknown namespace for symbol 'menu_layout_node_get_content'
../libmenu/menu-layout.h:126: Warning: MateMenu: symbol='menu_layout_node_set_content': Unknown namespace for symbol 'menu_layout_node_set_content'
../libmenu/menu-layout.h:128: Warning: MateMenu: symbol='menu_layout_node_get_content_as_path': Unknown namespace for symbol 'menu_layout_node_get_content_as_path'
../libmenu/menu-layout.h:130: Warning: MateMenu: symbol='menu_layout_node_root_get_name': Unknown namespace for symbol 'menu_layout_node_root_get_name'
../libmenu/menu-layout.h:131: Warning: MateMenu: symbol='menu_layout_node_root_get_basedir': Unknown namespace for symbol 'menu_layout_node_root_get_basedir'
../libmenu/menu-layout.h:133: Warning: MateMenu: symbol='menu_layout_node_menu_get_name': Unknown namespace for symbol 'menu_layout_node_menu_get_name'
../libmenu/menu-layout.h:134: Warning: MateMenu: symbol='menu_layout_node_menu_get_app_dirs': Unknown namespace for symbol 'menu_layout_node_menu_get_app_dirs'
../libmenu/menu-layout.h:135: Warning: MateMenu: symbol='menu_layout_node_menu_get_directory_dirs': Unknown namespace for symbol 'menu_layout_node_menu_get_directory_dirs'
../libmenu/menu-layout.h:137: Warning: MateMenu: symbol='menu_layout_node_move_get_old': Unknown namespace for symbol 'menu_layout_node_move_get_old'
../libmenu/menu-layout.h:138: Warning: MateMenu: symbol='menu_layout_node_move_get_new': Unknown namespace for symbol 'menu_layout_node_move_get_new'
../libmenu/menu-layout.h:140: Warning: MateMenu: symbol='menu_layout_node_legacy_dir_get_prefix': Unknown namespace for symbol 'menu_layout_node_legacy_dir_get_prefix'
../libmenu/menu-layout.h:141: Warning: MateMenu: symbol='menu_layout_node_legacy_dir_set_prefix': Unknown namespace for symbol 'menu_layout_node_legacy_dir_set_prefix'
../libmenu/menu-layout.h:143: Warning: MateMenu: symbol='menu_layout_node_merge_file_get_type': Unknown namespace for symbol 'menu_layout_node_merge_file_get_type'
../libmenu/menu-layout.h:144: Warning: MateMenu: symbol='menu_layout_node_merge_file_set_type': Unknown namespace for symbol 'menu_layout_node_merge_file_set_type'
../libmenu/menu-layout.h:146: Warning: MateMenu: symbol='menu_layout_node_merge_get_type': Unknown namespace for symbol 'menu_layout_node_merge_get_type'
../libmenu/menu-layout.h:148: Warning: MateMenu: symbol='menu_layout_node_default_layout_get_values': Unknown namespace for symbol 'menu_layout_node_default_layout_get_values'
../libmenu/menu-layout.h:149: Warning: MateMenu: symbol='menu_layout_node_menuname_get_values': Unknown namespace for symbol 'menu_layout_node_menuname_get_values'
../libmenu/menu-layout.h:151: Warning: MateMenu: symbol='MenuLayoutNodeEntriesChangedFunc': Unknown namespace for identifier 'MenuLayoutNodeEntriesChangedFunc'
../libmenu/menu-layout.h:153: Warning: MateMenu: symbol='menu_layout_node_root_add_entries_monitor': Unknown namespace for symbol 'menu_layout_node_root_add_entries_monitor'
../libmenu/menu-layout.h:154: Warning: MateMenu: symbol='menu_layout_node_root_remove_entries_monitor': Unknown namespace for symbol 'menu_layout_node_root_remove_entries_monitor'
../libmenu/menu-monitor.h:29: Warning: MateMenu: symbol='MenuMonitor': Unknown namespace for identifier 'MenuMonitor'
../libmenu/menu-monitor.h:36: Warning: MateMenu: symbol='MenuMonitorEvent': Unknown namespace for identifier 'MenuMonitorEvent'
../libmenu/menu-monitor.h:38: Warning: MateMenu: symbol='MenuMonitorNotifyFunc': Unknown namespace for identifier 'MenuMonitorNotifyFunc'
../libmenu/menu-monitor.h:41: Warning: MateMenu: symbol='menu_get_file_monitor': Unknown namespace for symbol 'menu_get_file_monitor'
../libmenu/menu-monitor.h:42: Warning: MateMenu: symbol='menu_get_directory_monitor': Unknown namespace for symbol 'menu_get_directory_monitor'
../libmenu/menu-monitor.h:44: Warning: MateMenu: symbol='menu_monitor_ref': Unknown namespace for symbol 'menu_monitor_ref'
../libmenu/menu-monitor.h:45: Warning: MateMenu: symbol='menu_monitor_unref': Unknown namespace for symbol 'menu_monitor_unref'
../libmenu/menu-monitor.h:47: Warning: MateMenu: symbol='menu_monitor_add_notify': Unknown namespace for symbol 'menu_monitor_add_notify'
../libmenu/menu-monitor.h:48: Warning: MateMenu: symbol='menu_monitor_remove_notify': Unknown namespace for symbol 'menu_monitor_remove_notify'
../libmenu/menu-util.h:35: Warning: MateMenu: symbol='menu_verbose': Unknown namespace for symbol 'menu_verbose'
../libmenu/menu-util.h:36: Warning: MateMenu: symbol='menu_debug_print_layout': Unknown namespace for symbol 'menu_debug_print_layout'
../libmenu/menu-util.h:41: Warning: MateMenu: symbol='menu_verbose': Unknown namespace for symbol 'menu_verbose'
../libmenu/menu-util.h:48: Warning: MateMenu: symbol='menu_debug_print_layout': Unknown namespace for symbol 'menu_debug_print_layout'
```

**Comment by yetist** [comment]
> This has now gotten more complex, this is a retest from scratch w the previous PR dependency etc

I think we should review and test #113 first, just build it with autotools is enough, compare the CI output, after #113 merged, then review this PR.

**Comment by yetist** [comment]
> The combined test branch (this applied on top of #115) builds with a bucket of "unknown namespace" warnings but does install and run (menu works normally on the mate-panel button menu). Used this configuration command: `meson setup build --prefix=/usr`

These warnings only reported on debian:
Debian: https://app.travis-ci.com/github/mate-desktop/mate-menus/jobs/593006508#L2189
Fedora: https://app.travis-ci.com/github/mate-desktop/mate-menus/jobs/593006509#L2101

**Comment by yetist** [comment]
I have a question, since the first commit 17e291fd05d66fe232e2f409d54331c495b2fbd0, the `LIB_MENU_LT_VERSION=6:9:4` in `configure.ac` has not changed, I think it's wrong.

I suggest that after fully switching to meson, the version of the library can be automatically generated by the version number.

**Comment by lukefromdc** [comment]
Wonder what causes the difference in ninja build warnings between Debian and Fedora? Meson/Ninja versions perhaps?

**Comment by zhuyaliang** [comment]
>>The combined test branch (this applied on top of https://github.com/mate-desktop/mate-menus/pull/115) builds with a bucket of "unknown namespace" warnings but does install and run (menu works normally on the mate-panel button menu).

I use archlinux, a lot of compilation warnings appear

**Comment by yetist** [comment]
This warning was reported by gobject-instospection: "Unknown namespace for identifier"

Because we use `MateMenu` as  the `identifier_prefix`, `matemenu` as the `symbol_prefix`, but these symbols is not start with the prefix.

**Comment by raveit65** [comment]
> Wonder what causes the difference in ninja build warnings between Debian and Fedora? Meson/Ninja versions perhaps?

After a `git rebase master & git push -f` on this branch the warnings are still there in fedora build. https://app.travis-ci.com/github/mate-desktop/mate-menus/jobs/600637026#L2129
So, no different.

**Comment by yetist** [comment]
I noticed that in the `build.ninja` file generated by meson, when the `g-ir-scanner` command is called, the `--warn-all` parameter is used, which will cause these warnings to appear.

`/usr/bin/g-ir-scanner --quiet --no-libtool --namespace=MateMenu --nsversion=2.0 --warn-all --output libmenu/MateMenu-2.0.gir`

**Comment by yetist** [comment]
Yes, I think the warning can be ignored.

**Comment by raveit65** [comment]
@yetist 
Can you please add your analyses of the issue to commit description.
https://github.com/mate-desktop/mate-menus/pull/113#issuecomment-1475757278
Than it is documented and we don't have to search in this PR for information's.

**Review by raveit65 — APPROVED** [review]
LGTM,
install and uninsall the package fine.

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine here with current changes, uninstall reports no errors and all files removed though did not check the directories

**Pull request merged**
