### PR TITLE
make mate-applications-merged symlink in ~/.config/menus if not exists

### PR DESCRIPTION
**Pull request by rezso**
https://github.com/mate-desktop/mate-menus/issues/2

### CODE REVIEW

**Comment by raveit65** [comment]
Ok, that works, the symlink ~.config/menus/mate-application-merged is there after a session restart.

**Comment by XRevan86** [comment]
https://github.com/GNOME/gnome-menus/commit/9d45c53 seems to be solving the same problem but without symlinks.

**Comment by raveit65** [comment]
@rezso 
XRevan86 is the primary maintainer of mate-menus, so can you please try out his suggestion?

**Comment by raveit65** [comment]
@XRevan86 
How should that work?
```
diff --git a/libmenu/gmenu-tree.c b/libmenu/gmenu-tree.c
index 3e59c2c..8e01af4 100644
--- a/libmenu/gmenu-tree.c
+++ b/libmenu/gmenu-tree.c
```
No, idea why you post this suggestions here....

**Comment by rezso** [comment]
@raveit65 
I tried, applied the gnome changes to mate-menus.
I can compile it without any errors.
After installing I re-installed the Zuma's revenge game with wine. The .menu files are in ~/.config/menus/applications-merged. So this works.
But I see the Zuma's revenge menu in the main menu/Others, instead os Wine/Programs/Popcap Games/Zuma's Revenge.

**Comment by raveit65** [comment]
@rezso 
I just tested your paste and it works here with installing free 'Simple Sudoku' in f26.
After using wine-program-launcher from right-click menu to install 'Simple Sudoku', i found the desktop files under main menu/Wine/Programs/simple sudoku/.
Same with installing Winamp with winetricks.
I did that in a VM under a fresh account.
So maybe we get different results with different applications, or with different wine versions?
```
[root@f26 rock]# rpm -qa wine*
wine-opencl-2.14-1.fc26.i686
wine-pulseaudio-2.14-1.fc26.x86_64
wine-alsa-2.14-1.fc26.i686
wine-cms-2.14-1.fc26.i686
wine-mono-4.7.1-1.fc26.noarch
wine-twain-2.14-1.fc26.x86_64
wine-symbol-fonts-2.14-1.fc26.noarch
wine-alsa-2.14-1.fc26.x86_64
wine-2.14-1.fc26.x86_64
winetricks-20170731-1.fc26.noarch
wine-ms-sans-serif-fonts-2.14-1.fc26.noarch
wine-common-2.14-1.fc26.noarch
wine-capi-2.14-1.fc26.i686
wine-times-new-roman-fonts-2.14-1.fc26.noarch
wine-cms-2.14-1.fc26.x86_64
wine-fonts-2.14-1.fc26.noarch
wine-desktop-2.14-1.fc26.noarch
wine-filesystem-2.14-1.fc26.noarch
wine-arial-fonts-2.14-1.fc26.noarch
wine-core-2.14-1.fc26.x86_64
wine-core-2.14-1.fc26.i686
wine-fixedsys-fonts-2.14-1.fc26.noarch
wine-system-fonts-2.14-1.fc26.noarch
wine-wingdings-fonts-2.14-1.fc26.noarch
wine-twain-2.14-1.fc26.i686
wine-systemd-2.14-1.fc26.noarch
wine-openal-2.14-1.fc26.x86_64
wine-openal-2.14-1.fc26.i686
wine-courier-fonts-2.14-1.fc26.noarch
wine-opencl-2.14-1.fc26.x86_64
wine-small-fonts-2.14-1.fc26.noarch
wine-marlett-fonts-2.14-1.fc26.noarch
wine-capi-2.14-1.fc26.x86_64
wine-ldap-2.14-1.fc26.i686
wine-pulseaudio-2.14-1.fc26.i686
wine-tahoma-fonts-2.14-1.fc26.noarch
wine-ldap-2.14-1.fc26.x86_64
```
sudoku42n_setup.exe i got from here http://www.chip.de/downloads/Simple-Sudoku_17291959.html

Edit: 
I found a free version here
http://herunterladen.freedownloadmanager.org/Windows-PC/Zuma-s-Revenge/KOSTENLOS-2.5.0.3.html

And the game is in 
i found the desktop files under main menu/Wine/Programs/PopCap Games/Zuma's Revenge!.

**Comment by raveit65** [comment]
Opps, forget what i said, i used wrong patch.
Testing again.....

**Comment by raveit65** [comment]
@rezso 
You're right .
The gnome patch doesn't fix the problem. All apps are under main menu/Others

@XRevan86 
Do you agree with merging the symlink version?
I know you're busy with exam, but this fixes a long outstanding issue, and you look for a better fix later if you have time again.

**Comment by raveit65** [comment]
I tested the changes from PR again and it works like a charm.

**Comment by raveit65** [comment]
Any way, i will use this for fedora build to get this out of my head.
@rezso 
Thanks

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-menus/commit/923a0d96b4de690e48e1ebd2efe9ff544cc7b254
Thanks

**Pull request closed without merging**
