### PR TITLE
Use datadir and libdir when install gir files

### PR DESCRIPTION
**Pull request by jumapico**
Currently gir generated files are installed in INTROSPECTION_GIRDIR and
INSTROSPECTION_TYPELIBDIR.

### CODE REVIEW

**Comment by selectiveduplicate** [comment]
This in the end amounts to the same directory. What's the difference then if I might ask? :confused:

**Comment by jumapico** [comment]
Compare with a similar file in [caja](https://github.com/mate-desktop/caja/blob/master/libcaja-extension/Makefile.am#L83).

The usage of $(INTROSPECTION_GIRDIR) ignores the --prefix param used in autogen.sh.

**Comment by lukefromdc** [comment]
What do we have (python program using mate-menus that can be installed outside Mint or Ubuntu) for testing this and finding any breakage?

Ignoring --prefix at configure could have ugly results, but I don't know enough about introspection or about python to know if $(INTROSPECTION_GIRDIR) has to be used or even can follow --prefix

**Comment by jumapico** [comment]
Gentle ping.

Please, consider that the same code is used in:

* [caja](https://github.com/mate-desktop/caja/blob/cbd6b367e9b05c08bff88ee1cfa03c09c7ee2558/libcaja-extension/Makefile.am#L83)
* [eom](https://github.com/mate-desktop/eom/blob/9cf6d58d8ace54a95d6f9065cfcff1782f34eeaf/src/Makefile.am#L221)
* [libmatekbd](https://github.com/mate-desktop/libmatekbd/blob/7fa15ab9b36383f799fe306a68c2449896f071bd/libmatekbd/Makefile.am#L126)
* [mate-desktop](https://github.com/mate-desktop/mate-desktop/blob/90f305344547fb47a26b6a5fbb4434effed7d83b/libmate-desktop/Makefile.am#L125)
* [pluma](https://github.com/mate-desktop/pluma/blob/fad391d7cd59138991583b8a199096225786ea29/pluma/Makefile.am#L208)

**Comment by raveit65** [comment]
@monsta @sc0w 
Does this works for debian/ubuntu?
If yes review/merge it,    or not :)

**Pull request merged**
