### PR TITLE
build: allow users to disable gettext support (--disable-nls)

### PR DESCRIPTION
**Pull request by rbuj**
### With NLS
```
$ find /usr/share/locale -type f -name 'mate-menus.mo' -exec sudo rm -f {} +
$ ./autogen.sh --prefix=/usr && make && sudo make install
$ find /usr/share/locale -type f -name 'mate-menus.mo' -exec du -ch {} + | grep total
552K	total
$ du -h /usr/share/mate/desktop-directories
84K	/usr/share/mate/desktop-directories
```
### Without NLS
```
$ find /usr/share/locale -type f -name 'mate-menus.mo' -exec sudo rm -f {} +
$ ./autogen.sh --prefix=/usr --disable-nls && make && sudo make install
$ find /usr/share/locale -type f -name 'mate-menus.mo' -exec du -ch {} + | grep total
$ du -h /usr/share/mate/desktop-directories
84K	/usr/share/mate/desktop-directories
```

### CODE REVIEW

**Comment by raveit65** [comment]
Configure --help gives me
```
--disable-nls           do not use Native Language Support
```
Why not using the same naming in in config summary?
```
-Gettext support:              no
+Native Language support:              no
```
I don't think that most users know for what `gettext` is good for.

Rest looks good.
`/usr/local/share/help` and `/usr/local/share/locale` are empty when building with `--disable-nls`.

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
@yetist 
Looks like something is wrong with actual ArchLinux docker image?
https://travis-ci.org/github/mate-desktop/mate-menus/jobs/757908594

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
